coverage:
  status:
    project:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags:
          - unittests
      karma:
        enabled: true
        target: 90%
        threshold: 10%
        base: auto
        flags:
          - karma
      jest:
        enabled: true
        target: 36%
        threshold: 10%
        base: auto
        flags:
          - jest
      integration:
        enabled: true
        target: 65%
        threshold: 10%
        base: auto
        flags:
          - integration
    patch:
      default: off
      unittests:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags: 
          - unittests
      karma:
        enabled: true
        target: 90%
        threshold: 10%
        base: auto
        flags:
          - karma
      jest:
        enabled: true
        target: 50%
        threshold: 10%
        base: auto
        flags:
          - jest
      integration:
        enabled: true
        target: 80%
        threshold: 10%
        base: auto
        flags:
          - integration
flags:
  integration:
    paths:
      - bundles/core/
      - examples/bundle/
  unittests:
    paths:
      - bundles/core/
      - examples/bundle/
  karma:
    paths:
      - ui.apps/
  jest:
    paths:
      - react-components/