categories:
  - title: "Features & Enhancements"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
template: |
  ## Changes

  $CHANGES
